config/routes.rb
Coingiving::Application.routes.draw do

  get "sponsor/profile"
  patch "sponsor/update_profile"
  get "sponsor/projects"
  get "sponsor/donations"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :sponsors

  resources :sponsors, only: [:show, :index]

  root 'home#index'

  get '/blockchain_info_callback' => "home#blockchain_info_callback", :as => "blockchain_info_callback"
  get '/project_sponsors' => "home#project_sponsors", :as => "project_sponsors"

  resources :projects do
    member do
      get 'generate_address'
    end
  end

  

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  include Concerns::DonationsCache
  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :url, url: true

  has_many :deposit_addresses
  has_many :deposits, :through => :deposit_addresses
  has_many :projects, -> { where('deposit_addresses.year_donations > 0') }, :through => :deposit_addresses
  # todo fix to whole time donations ^^^

  scope :public_only, -> { where(:private_donations => false) }

  scope :confirmed, -> { where("confirmed_at is not ?", nil) }

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def project_budget project_id
    deposit_address = deposit_addresses.find_by_project_id(project_id)
    if deposit_address.nil?
      0
    else
      deposit_address.update_donations_cache if deposit_address.year_donations.nil?
      deposit_address.year_donations
    end
  end

end

app/controllers/sponsor_controller.rb
class SponsorController < ApplicationController

  before_filter :authenticate_sponsor!

  def profile
  end

  def update_profile
    if current_sponsor.update sponsor_params
      redirect_to sponsor_profile_path, notice: 'Profile updated'
    else
      render :profile
    end
  end

  def projects
    @projects = current_sponsor.projects.page(params[:page]).per(30)
  end

  def donations
    @deposits = current_sponsor.deposits.order(:created_at => :desc).page(params[:page]).per(30)
  end

    private

  def sponsor_params
    params.require(:sponsor).permit(:name, :url, :location, :private_donations)
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < InheritedResources::Base

  def index
    @sponsors = Sponsor.confirmed.order(name: :asc).order(year_donations: :desc).page(params[:page]).per(30)
  end

  def show
    @sponsor = Sponsor.find(params[:id])
    @deposits = @sponsor.deposits.order(:created_at => :desc).page(params[:page]).per(30)
  end

end

app/views/sponsor/_menu.html.slim
ul.nav.nav-pills.nav-stacked
  li class=(%w(profile update_profile).include?(action_name) ? 'active' : '')
    a href=sponsor_profile_path
      | Profile
  li class=(%w(projects).include?(action_name) ? 'active' : '')
    a href=sponsor_projects_path
      | Supported Projects
  li class=(%w(donations).include?(action_name) ? 'active' : '')
    a href=sponsor_donations_path
      | Donations

app/views/sponsor/donations.html.slim
.row.sponsor-page
  .col-md-3
    = render 'menu'
  .col-md-9
    = render partial: 'sponsors/deposits', locals: {deposits: @deposits}

app/views/sponsor/profile.html.slim
.row.sponsor-page
  .col-md-3
    = render 'menu'
  .col-md-9
    = twitter_bootstrap_form_for(current_sponsor, :url => sponsor_update_profile_path, html: {}) do |f|
      = f.text_field :name, :autofocus => true
      = f.text_field :url
      = f.text_field :location
      = f.label :private_donations do
        = f.check_box :private_donations
        |  Hide the list projects I helped
      .form-group
        label Avatar
        div 
          = gravatar_image_tag current_sponsor.email, gravatar: {size: 25}
          |  
          = link_to 'Change the avatar at gravatar.com.', 'https://www.gravatar.com/', target: '_blank'
      = f.submit 'Save'

app/views/sponsor/projects.html.slim
.row.sponsor-page
  .col-md-3
    = render 'menu'
  .col-md-9
    table.table
      thead
        tr
          th Project
          th Description
          th Donated
      tbody
        - @projects.each do |project|
          tr
            td
              strong= link_to project.name, project
            td= project.about
            td= btc_human current_sponsor.deposits.by_project(project).sum(:amount)
    = paginate @projects