config/routes.rb
Coingiving::Application.routes.draw do

  get "sponsor/profile"
  patch "sponsor/update_profile"
  get "sponsor/projects"
  get "sponsor/donations"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :sponsors

  resources :sponsors, only: [:show, :index]

  root 'home#index'

  get '/blockchain_info_callback' => "home#blockchain_info_callback", :as => "blockchain_info_callback"
  get '/project_sponsors' => "home#project_sponsors", :as => "project_sponsors"

  resources :projects do
    member do
      get 'generate_address'
    end
  end

  

end

app/controllers/home_controller.rb
require 'uri'
require 'open-uri' 
require 'net/http'

class HomeController < ApplicationController
  
  def index
    @projects = Project.moderated.order(moderated_at: :desc).page(params[:page]).per(20)
    @sponsors = Sponsor.order(year_donations: :desc).where('year_donations > 0').page(params[:page]).per(12)
  end

  def project_sponsors
    @project = Project.find_by_url(params[:url]) || create_project(params[:url])

    if @project.nil?
      redirect_to root_path, :notice => "Project not found / creation failed"
    else
      @deposit_address = @project.deposit_address(current_sponsor)
      limit = (params[:limit] || 6).to_i
      limit =  20 if limit > 20
      @project_sponsors = @project.sponsors.public_only.order(year_donations: :desc).first(limit)
      @show_sponsors = params[:mode].nil? || (params[:mode]=="sponsors")
      @show_buttons  = params[:mode].nil? || (params[:mode]=="buttons")
      render :layout => "iframe"
    end

  end

  def create_project url
    Rails.logger.info "Creating project: #{url}"
    begin
      doc = Nokogiri::HTML(open(url))
      # iframe_tag = doc.search("iframe[src='http://coingiving.com/project_sponsors?url=#{url}']").first
      title = doc.search('[data-coingiving="title"]').first.text rescue nil
      description = doc.search('[data-coingiving="description"]').first.text rescue nil
      bitcoin_address = doc.search('[data-coingiving="bitcoin-address"]').first.text rescue nil

      # if (iframe_tag.count > 0) && title && description && bitcoin_address
      if title && description && bitcoin_address
        # Rails.logger.info "  iframe: #{iframe_tag.inspect} title: #{title} description: #{description} bitcoin_address: #{bitcoin_address}"
        Rails.logger.info "  title: #{title} description: #{description} bitcoin_address: #{bitcoin_address}"
        Project.create({url: url, name: title, about: description, bitcoin_address: bitcoin_address, donation_page_url: url})
      else
        # Rails.logger.info "  something is missing iframe: #{iframe_tag.inspect} title: #{title} description: #{description} bitcoin_address: #{bitcoin_address}"
        Rails.logger.info "  something is missing: title: #{title} description: #{description} bitcoin_address: #{bitcoin_address}"
        nil          
      end

    rescue StandardError => e
      Rails.logger.info e.inspect
      nil
    end
  end

  def blockchain_info_callback
  # todo: check if remote IP address belongs to blockchain.info

    if (params[:secret]!=CONFIG["blockchain_info"]["callback_secret"])
      Rails.logger.error "Invalid secret #{params.inspect}!"      
      render :text => "Invalid secret #{params.inspect}!" 
      return
    end

    test = params[:test]

    if params[:value].to_i < 0
      Rails.logger.info "*ok*"
      render :text => "*ok*";
      return
    end

    if deposit = Deposit.find_by_input_tx(params[:input_transaction_hash])
      deposit.update_attribute(:confirmations, confirmations = params[:confirmations] ) if !test
      if confirmations.to_i > 6 
        Rails.logger.info "*ok*"
        render :text => "*ok*"
      else
        Rails.logger.info "Deposit #{deposit.id} updated!"
        render :text => "Deposit #{deposit.id} updated!"
      end
      return
    end

    if deposit_address = DepositAddress.find_by_bitcoin_address(params[:input_address])
      (
        deposit = Deposit.create({
          deposit_address_id: deposit_address.id,
          input_tx: params[:input_transaction_hash],
          output_tx: params[:transaction_hash],
          confirmations: params[:confirmations],
          amount: params[:value].to_i
        })
      ) if !test     
      Rails.logger.info "Deposit created! #{deposit.inspect}"
      render :text => "Deposit #{deposit[:txid]} has been created!"
      deposit_address.update_donations_cache
    else
      Rails.logger.error "Error: Project with deposit address #{params[:input_address]} is not found!"
      render :text => "Project with deposit address #{params[:input_address]} is not found!"
    end    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
.jumbotron
  h1 Personified Bitcoin Donations
  div
    p Donors can donate to projects thus becoming their sponsors.
    p Projects can use our widget to show sponsors' gravatars on their sites.
    p
      | Donations are instantly forwarded to recipients free of charge by 
      = link_to "Blockchain.info", "https://blockchain.info/api/api_receive", terget: :blank
      | .

.row
  .col-md-4
    h1 New Projects
    ul
      - @projects.each do |project|
        li= link_to project.name, project
  .col-md-8.well
    h1 Top Sponsors
    - @sponsors.in_groups_of(4, false) do |sponsors|
      .row
        - sponsors.each do |sponsor|
          .col-sm-3.col-md-3
            .thumbnail
              = link_to gravatar_image_tag(sponsor.email, alt: sponsor.name, class: 'img-responsive', gravatar: {size: 300}), sponsor
              .caption
                h5= btc_human sponsor.deposits.sum(:amount)
                small= link_to sponsor.name, sponsor

app/views/home/project_sponsors.html.slim
- if @show_sponsors
  p.centered
    - @project_sponsors.each do |sponsor|
      = link_to gravatar_image_tag(sponsor.email, alt: sponsor.name, gravatar: {size: 100}), sponsor, target: '_blank'
      |  

  p.centered
    = t 'iframe.project_sponsors_count', count: @project.sponsors.count
    - if @project.sponsors.count > 0
      |   
      a href=project_url(@project) target='_blank' see all

- if @show_buttons
  - if current_sponsor
    - if @deposit_address.nil?
      p.centered = link_to 'Become a Sponsor', generate_address_project_path(@project), class: 'btn btn-success'
    - else
      p.centered
        = link_to gravatar_image_tag(current_sponsor.email, gravatar: {size: 23}), sponsor_url(current_sponsor)
        |  
        = link_to current_sponsor.name, sponsor_url(current_sponsor), target: :blank
        | , please donate (> 0.001 Ƀ) to:
      p.centered
        = @deposit_address.bitcoin_address
      .qrcode.centered data-qrcode="bitcoin:#{@deposit_address.bitcoin_address}"

  - else
    p.centered 
      | Please 
      = link_to "Sign in", new_sponsor_session_url, target: :blank
      |  at CoinGiving.com and reload the page or donate anonymously to this address:
    p.centered
      = @project.bitcoin_address
    .qrcode.centered data-qrcode="bitcoin:#{@project.bitcoin_address}"

  p.centered
    | Don't know how to donate? 
    a href="https://weusecoins.com/" target='_blank' Learn about Bitcoin »
      