config/routes.rb
Coingiving::Application.routes.draw do

  get "sponsor/profile"
  patch "sponsor/update_profile"
  get "sponsor/projects"
  get "sponsor/donations"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :sponsors

  resources :sponsors, only: [:show, :index]

  root 'home#index'

  get '/blockchain_info_callback' => "home#blockchain_info_callback", :as => "blockchain_info_callback"
  get '/project_sponsors' => "home#project_sponsors", :as => "project_sponsors"

  resources :projects do
    member do
      get 'generate_address'
    end
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  include Concerns::DonationsCache
  
  has_many :deposit_addresses
  has_many :deposits, :through => :deposit_addresses
  has_many :sponsors, -> { where('deposit_addresses.year_donations > 0') }, :through => :deposit_addresses

  validates :url, presence: true, uniqueness: true, url: true
  validates :donation_page_url, presence: true, uniqueness: true, url: true

  validates :bitcoin_address, presence: true, bitcoin_address: true

  validates :name, presence: true
  validates :about, presence: true

  scope :moderated, -> { where("moderated_at is not ?", nil) }

  def deposit_address user
    user.nil? ? nil : DepositAddress.find_by_project_id_and_sponsor_id(id, user.id)    
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.moderated.order(name: :asc).order(year_donations: :desc).page(params[:page]).per(30)
    unless params[:search].blank?
      @projects = @projects.search(:name_or_about_contains => params[:search]).result
    end
  end

  def show
    @project = Project.find params[:id]
    @deposit_address = @project.deposit_address(current_sponsor)
    @project_sponsors = @project.sponsors.public_only.order(year_donations: :desc)
  end

  def generate_address
    unless current_sponsor && (@project = Project.find params[:id])
      redirect_to root_path
      return
    end

    @deposit_address = DepositAddress.find_by_project_id_and_sponsor_id(@project.id, current_sponsor.id)

    if @deposit_address.nil?
      uri = URI("https://blockchain.info/api/receive")
      params = {
        method: "create",
        address: @project.bitcoin_address,
        callback: "http://coingiving.com/blockchain_info_callback?secret=#{CONFIG["blockchain_info"]["callback_secret"]}"
      }
      uri.query = URI.encode_www_form(params)
      p uri
      res = Net::HTTP.get_response(uri)
      p res
      if res.is_a?(Net::HTTPSuccess) && (bitcoin_address = JSON.parse(res.body)["input_address"])
        DepositAddress.create({project_id: @project.id, sponsor_id: current_sponsor.id, bitcoin_address: bitcoin_address})
      end
    end
    redirect_to :back
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.slim
h1 Supported Projects
p
  = form_tag projects_path, html: {role: 'form', class: 'form-inline"'}, method: :get do |f|
    .form-group
      .row
        .col-lg-10
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search'
        .col-lg-2
          button type="submit" class="btn form-control btn-default" Find project
p
  table.table
    thead
      tr
        th Project
        th Description
        th Sponsors
        th Donated/year
    tbody
      - @projects.each do |project|
        tr
          td
            strong= link_to project.name, project
          td= project.about
          td= project.sponsors.count
          td= btc_human project.year_donations
  = paginate @projects

app/views/projects/show.html.slim
- content_for :title do
  | Donate Bitcoins to 
  = @project.name
- content_for :description do
  = @project.about

h2 
  = @project.name
- unless @project.moderated_at
  .alert
    strong Be careful!
    |  This project has not been moderated by CoinGiving. Please, check the project 
    = link_to 'website', @project.url, target: :blank
    - if @project.donation_page_url && @project.url != @project.donation_page_url
      |  and 
      = link_to 'donation page', @project.donation_page_url, target: :blank
    |  to make sure it's trustable before donating. If it is not please 
    = mail_to 'contact@anonymousads.com', 'report to us'
    | .
.row
  .col-md-5
    h3 
      | Project 
      = link_to 'website', @project.url, target: :blank
      - if @project.donation_page_url && @project.url != @project.donation_page_url
        |  and 
        = link_to 'donation page', @project.donation_page_url, target: :blank
    h3 Description
    blockquote = simple_format @project.about

    h3 Share
    / AddThis Button BEGIN
    .addthis_toolbox.addthis_default_style.addthis_32x32_style(addthis:data_track_clickback="false" addthis:data_track_addressbar="false")
      a.addthis_button_preferred_1
      a.addthis_button_preferred_2
      a.addthis_button_preferred_3
      a.addthis_button_preferred_4
      a.addthis_button_compact
      a.addthis_counter.addthis_bubble_style
    / AddThis Button END

    h3 Donate
    div style="min-height:150px"
      - if current_sponsor.nil?
        p
          | Please 
          = link_to 'sign in', new_sponsor_session_path
          |  to generate Bitcoin address for donatoins.
      - else
        - if @deposit_address.nil?
          p = link_to 'Generate Bitcoin Address For Donations', generate_address_project_path(@project), class: 'btn btn-success'
        - else
          .qrcode data-qrcode="bitcoin:#{@deposit_address.bitcoin_address}"
          p
            | Deposit any amount (> 0.001 Ƀ) to support this project!
          p 
            = @deposit_address.bitcoin_address
      p =link_to "What is Bitcoin?", "http://weusecoins.com", target: :blank

  .col-md-7

    h3 Sponsors
    p
      - @project_sponsors.in_groups_of(4, false) do |sponsors|
        .row
          - sponsors.each do |sponsor|
            .col-sm-3.col-md-3 style="min-width:150px"
              .thumbnail
                = link_to gravatar_image_tag(sponsor.email, alt: sponsor.name, class: 'img-responsive', gravatar: {size: 150}), sponsor
                .caption
                  h5= btc_human sponsor.project_budget(@project.id)
                  small= link_to sponsor.name, sponsor


    p = t 'iframe.project_sponsors_count', count: @project.sponsors.count

app/views/projects/sponsors.html.slim
a href=project_path(@project) target='_blank'
  | Support 
  = @project.name
  |  through CoinGiving.com

p.sponsors-list
  - @project_sponsors.each do |sponsor|
    = link_to gravatar_image_tag(sponsor.email, alt: sponsor.name, gravatar: {size: 100}), sponsor, target: '_blank'
    |  

p = t 'iframe.project_sponsors_count', count: @project_sponsors.count