config/routes.rb
Coingiving::Application.routes.draw do

  get "sponsor/profile"
  patch "sponsor/update_profile"
  get "sponsor/projects"
  get "sponsor/donations"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :sponsors

  resources :sponsors, only: [:show, :index]

  root 'home#index'

  get '/blockchain_info_callback' => "home#blockchain_info_callback", :as => "blockchain_info_callback"
  get '/project_sponsors' => "home#project_sponsors", :as => "project_sponsors"

  resources :projects do
    member do
      get 'generate_address'
    end
  end

  

end

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="" name="description"
    meta content="" name="author"
    meta name="globalsign-domain-verification" content="4s0HtpeRymKXiHhGr-hodffrlPYbkxK9rg_MnNOqba"
    link href="/favicon.png" rel="shortcut icon"
    
    title= "CoinGiving — " + (content_for?(:title) ? yield(:title) : "Donate Bitcoins")

    meta name='description' content=(content_for?(:description) ? yield(:description) : "Donate bitcoins to make world better place.")
    meta name='keywords' content='charity,help,giving,donor,open source,cotribute,community,bitcoin'
    meta property='og:image' content=asset_path('bitcoinLogo1000.png')
    link rel='image_src' type='image/png' href=asset_path('bitcoinLogo1000.png')

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    
    = csrf_meta_tags
  body
    = render 'common/ga'
    .container
      .masthead
        .pull-right
          small
            - if current_sponsor
              = link_to gravatar_image_tag(current_sponsor.email, gravatar: {size: 23}), current_sponsor
              |  
              = link_to current_sponsor.name, current_sponsor
              |  / 
              = link_to 'Account', sponsor_profile_path
              |  / 
              = link_to 'Sign Out', destroy_sponsor_session_path, method: :delete
            - else
              a href=new_sponsor_session_path Sign in
              |  / 
              a href=new_sponsor_registration_path Sign up
        h3.text-muted.code-pro CoinGiving
        = render 'common/menu'
      - if flash[:alert]
        br
        .alert= flash[:alert]
      - if flash[:notice]
        br
        .alert.alert-info= flash[:notice]
      = yield

      /! Site footer
      .footer
        p
          | © 
          = link_to 'CoinGiving', 'http://coingiving.com/', target: '_blank'
          |  2013-#{Date.today.year}. 
          | Source code is available at #{link_to('GitHub', 'https://github.com/tip4commit/coingiving', target: '_blank')} and you can also #{link_to('support', 'https://tip4commit.com/github/tip4commit/coingiving')} its development. 
          = link_to('Suggest new project', 'https://bitcointalk.org/index.php?topic=340692.msg3653056', target: '_blank')
          | .
    /! /container
    /!
      | Bootstrap core JavaScript
      | \==================================================
    /! Placed at the end of the document so the pages load faster\

app/views/layouts/iframe.html.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="" name="description"
    meta content="" name="author"
    link href="/favicon.png" rel="shortcut icon"
    
    title= "CoinGiving — " + (content_for?(:title) ? yield(:title) : "Donate Bitcoins")

    meta name='description' content=(content_for?(:title) ? yield(:title) : "Donate bitcoins to make world better place.")
    meta name='keywords' content='charity,help,giving,donor,open source,cotribute,community,bitcoin'
    /! %meta{:property => 'og:image', :content => asset_path('logo.png')}
    /! %link{:rel => 'image_src', :type => 'image/png', :href => asset_path('logo.png')}

    = stylesheet_link_tag    "iframe", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    
    = csrf_meta_tags
  body
    = render 'common/ga'
    = yield